# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be

include: package:flutter_lints/flutter.yaml

linter:

  # https://dart-lang.github.io/linter/lints/index.html.

  # `// ignore_for_file: name_of_lint` syntax on the line or in the file

  rules:
    prefer_const_constructors: false,
    use_key_in_widget_constructors: false

# https://dart.dev/guides/language/analysis-options
